### ISSUE TITLE
Gatsby build error with create-remote-file-node and Librestream-OnsightTechnicalServiceProgramv3.0.pdf

### ISSUE THREAD

**Issue by lsdrew** [ocupop/librestream#93]
About every second commit results in a specific build error that looks like this:
Error: url passed to create-remote-file-node is either missing or not a proper web uri: /media/Librestream-OnsightTechnicalServiceProgramv3.0.pdf
    at module.exports (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js:426:7)
    at remoteFileNode.retries (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-remote-media-item-node.js:314:26)
...
Triggering another build allows the build to complete without errors.

**Comment by tbeck** [comment]
@lsdrew - I believe that this happens when a media file is referenced but is still being processed by WP. ie... someone is making content updates and uploading files that then need to be processed by WP but a build is triggered at the same time. The reference to the file is there, but the file is not ready yet.
